#!/usr/bin/env php
<?php

require_once __DIR__ . "/vendor/autoload.php";

use Carbon\Carbon;
use \League\CLImate\CLImate;

$climate = new CLImate;

$climate->arguments->add([
    'webhook-url' => [
        'prefix'       => 'wu',
        'longPrefix'   => 'webhook-url',
        'description'  => 'URL of the webhook',
        'required'    => true,
    ],
    'deadline' => [
        'prefix'      => 'd',
        'longPrefix'  => 'deadline',
        'description' => 'Specify the deadline in ISO format: yyyy-mm-dd',
        'required'    => true,
    ],
    'event' => [
        'prefix'      => 'e',
        'longPrefix'  => 'event',
        'description' => 'Name of the deadline event',
        'required'    => true,
    ],
]);

$climate->arguments->parse();

$webhookUrl = $climate->arguments->get('webhook-url');
$deadline = $climate->arguments->get('deadline');
$event = $climate->arguments->get('event');

$from = new Carbon();
$to = Carbon::parse($deadline);

$text = sprintf(
        '%d days until %s',
        $to->diffInWeekdays($from),
        $event ?? $deadline
);

$data = [
    'text' => $text,
];


$client = new \GuzzleHttp\Client();
$client->post($webhookUrl, ['json' => $data], [
    'Content-Type' => 'application/json',
]);